### ISSUE TITLE
Refactor the decode_* and encode_* methods in packet.rs

### ISSUE THREAD

**Issue by 1c3t3a** [1c3t3a/rust-socketio#1]
Currently those methods receive a `Vec<u8>`, it might be better to work directly on `[u8]` or otherwise [`Bytes`](https://docs.rs/bytes/0.4.10/bytes/struct.Bytes.html). This should not be a very extensive task.

**Comment by kw-fn** [comment]
just looking at this and wondering if there was a way of doing this without
using unsafe code or will the offsets for the [u8] always be fixed?

**Comment by 1c3t3a** [comment]
I don't think that this would be a problem, as we would work on a bytes slice `&[u8]`. I've thought this through and maybe  [Bytes](https://docs.rs/bytes/1.0.0/bytes/struct.Bytes.html) would be the best solution as it presents itself as a fast and easy container for slices plus the [corresponding reqwest API method](https://docs.rs/reqwest/0.11.0/reqwest/struct.Response.html#method.bytes) from where the bytes are taken (at the moment), returns `Bytes`.

**Comment by 1c3t3a** [comment]
Closed via #28.
