### ISSUE TITLE
Switch websocket library

### ISSUE THREAD

**Issue by 1c3t3a** [1c3t3a/rust-socketio#115]
This library currently uses [the websocket crate](https://github.com/websockets-rs/rust-websocket/). However the library looks kind of abandoned and might not be the best fit for future plans like `async / await` support. Currently the library provides async support based on `tokio` 0.1. This could lead to problems and there are no real plans to get the support running with websocket (see [#242](https://github.com/websockets-rs/rust-websocket/issues/242)). It's also not to be expected that the library will provide support in case we have a problem, so switching the library might be a good idea. A battle proven implementation is provided by `tungstenite-rs` (async [here](https://github.com/snapview/tokio-tungstenite), blocking [here](https://github.com/snapview/tungstenite-rs)). What do you think @nshaaban-cPacket?

**Comment by nshaaban-cPacket** [comment]
Sounds good, might be worth doing before the engineio crate goes public? I'm not interested in implementing the change in the near future (only if it causes headache with 0.5.0).

**Comment by 1c3t3a** [comment]
Alright, I could implement it as soon as refactoring is merged. Also a good point that this should be done before engine.io goes public, then I am not tied to a certain API.

**Comment by nshaaban-cPacket** [comment]
> Alright, I could implement it as soon as refactoring is merged. Also a good point that this should be done before engine.io goes public, then I am not tied to a certain API.

Doesn't necessary have to be before, but might make sense. Ideally what library we are using internally for websockes/polling would not be exposed anyways.

**Comment by nshaaban-cPacket** [comment]
websocket *is* exposed here https://github.com/1c3t3a/rust-socketio/blob/9b1183b0313b52b82bb9e09f7c75f223cb9958ee/engineio/src/error.rs#L44

Plus we'll need the https://docs.rs/tungstenite/0.15.0/tungstenite/fn.client_tls_with_config.html to continue supporting passing in a TlsConnector

**Comment by nshaaban-cPacket** [comment]
May want to escalate this @1c3t3a websocket (latest) depends on hyper 0.10.6 which is vulnerable to RUSTSEC-2021-0079 and RUSTSEC-2021-0078 (found using cargo-audit)

**Comment by vi** [comment]
`websocket` crate is basically unmaintained now. Switching to `tungstenite` is recommended.

---

Does it make sense to release a new version of `websocket` crate that just points to (reexports) `tungstenite` and `tokio-tungstenite`, to prevent new accidental dependencies on the unmaintained code? Would benefits outweigh the harm? Currently `websocket` crate contains a warning in README:

> Note: Maintainership of this project is slugglish. You may want to use tungstenite or tokio-tungstenite instead.

Have you missed it what you were shopping around for a Websocket library?

**Comment by 1c3t3a** [comment]
Hi @vi, first of all thanks for the quick help! We originally wanted to switch to tungstenite, but the problem is that the sync version of it is by far slower than websocket.

> Observed significant performance degradation (25s minimum, peak of 75s) in the following case (client::socket::test::socket_io_integration):
> - Callback mode (where there is a separate thread constantly calling poll)
> - Attempt to send packets on the clone of the socket returned
> - Observe that websocket connection is busy reading
> - When a ping packet is received it is possible that the lock switches to the write
> - Socket finally sends a message

This is due to sync tungstenite not supporting the `.split` operation on their sender / receiver stream, something that websocket is capable of. The long time goal is definitely to switch to `tokio-tungstenite` (which is way faster), but we didn't make the switch yet, as this requires quite a lot of restructuring internally.

When I started the project about a year ago I didn't see the warning on web sockets Readme (I don't know if it wasn't there of if I just missed it), but the API seemed fine and the project was a bit more vivid then now.

**Comment by vi** [comment]
> This is due to sync tungstenite not supporting the .split operation on their sender / receiver stream

Note that `rust-websocket`s support for splitting sync sockets is only reliable only for non-encrypted `ws://` websockets. Maybe that's why sync `tungstenite` does not expose this function.

Splitting should work properly for async, including for `wss://`.

**Comment by vi** [comment]
> When I started the project about a year ago I didn't see the warning on web sockets Readme (I don't know if it wasn't there of if I just missed it)

It is more than a year ago: https://github.com/websockets-rs/rust-websocket/commit/b4f50dd7e18047bd085c8b9585cb6250ee2c7f7d

**Comment by 1c3t3a** [comment]
> It is more than a year ago: [websockets-rs/rust-websocket@b4f50dd](https://github.com/websockets-rs/rust-websocket/commit/b4f50dd7e18047bd085c8b9585cb6250ee2c7f7d)

Then I missed it :D

**Comment by 1c3t3a** [comment]
> > This is due to sync tungstenite not supporting the .split operation on their sender / receiver stream
> 
> Note that `rust-websocket`s support for splitting sync sockets is only reliable only for non-encrypted `ws://` websockets. Maybe that's why sync `tungstenite` does not expose this function.
> 
> Splitting should work properly for async, including for `wss://`, both in `rust-websocket` and `tokio-tungstenite`.

Yeah that's true, but it still feels like this is taking away potential speed. But we might change this, @nshaaban-cPacket suggested to internally use async to speed things up, that might now be the best solution.

**Comment by nshaaban-cPacket** [comment]
> Yeah that's true, but it still feels like this is taking away potential speed. But we might change this, @nshaaban-cPacket suggested to internally use async to speed things up, that might now be the best solution.
Using async internally has it's drawbacks too, we'd have to use a tokio runner (term might be wrong) internally for method calls, which is far from ideal, not to mention also has a performance hit. We may be able to support roughly the same API in asnyc (as most of it is callback based anyways), would require more thought.

**Comment by armoha** [comment]
There is also `async-tungstenite` [here](https://github.com/sdroege/async-tungstenite), which is not bound to any specific async runtime.
