### ISSUE TITLE
Support handler for any custom event

### ISSUE THREAD

**Issue by kappa** [1c3t3a/rust-socketio#128]
In Javascript client that works like:
```
socket.on('*', handler);
```

Without this it is required for the client to always know all events that the server can emit and set up separate handlers to all of them.

**Comment by nshaaban-cPacket** [comment]
> BTW, I managed to retrofit some v3 support into the current master but then got blocked on pings which go in the opposite direction in v3 and are hard to implement in the current sync codebase.

Consider cloning the client object (most of the paramaters are arc mutex locked anyways) then send it into a different thread that just sends the pings.

**Comment by marekvospel** [comment]
@1c3t3a this issue should probably be closed
