### ISSUE TITLE
improve existing test coverage

### ISSUE THREAD

**Issue by kw-fn** [1c3t3a/rust-socketio#13]
this issue is meant to stand in as a low-priority to-do item for eventually
moving the test cases from original source files into a `tests/` directory, it
may also be used to track the coverage of tests up until then and other
immediate testing related issues not specific to GH or CI/CD

**Comment by 1c3t3a** [comment]
We might also add a coverage checker to the repo, maybe [Codecov](https://github.com/marketplace/codecov/). But this only makes sense if the containerized tests are up and running.

**Comment by 1c3t3a** [comment]
I've thought this through and IMO the tests in each file are clearly easier to grasp and understand than when they're in a separate file.

**Comment by 1c3t3a** [comment]
Further information about how the pipeline and the test suite is set up can be found at `ci/README.md`.

**Comment by nshaaban-cPacket** [comment]
Code coverage is a staggering 88% (will be higher once https://github.com/1c3t3a/rust-socketio/issues/45 is fixed), is this still needed @1c3t3a ?
