### ISSUE TITLE
Add optional query params on connect

### ISSUE THREAD

**Issue by DavyJo** [1c3t3a/rust-socketio#131]
Some APIs require authentication by query parameters (e.g. FXCM REST API) by appending a &key=val to the url. In said case this is only required once on login to get session authentication infos and not part of every request.

**Comment by 1c3t3a** [comment]
Mhh... did you try to provide an URL where these parameters are already set? I think it should work as this crate passes around the `URL` type, which is parsed directly after receiving the string of the URL.

**Comment by 1c3t3a** [comment]
Closing because of missing specification.

**Comment by RyannnnnWong** [comment]
maybe this:
var client = io("https:xxx.com/", 
                         transport = [websocket], 
                         query = {"uuid" = ''});

add a function like "query" in rust-socketio?
