### ISSUE TITLE
Packing with musl causes segfault

### ISSUE THREAD

**Issue by editso** [1c3t3a/rust-socketio#142]
![ONJK93D6%DS$H%Z{}3DQ`TJ](https://user-images.githubusercontent.com/37452715/147767334-22171a5e-e32f-4022-badd-578313c28769.png)
![QT)TPUL4IZ639UZAL2C331Q](https://user-images.githubusercontent.com/37452715/147767352-b1fb4eaa-9e91-4ac2-9d83-a37d6b8b8fa0.png)

Version: 0.3.0

**Comment by 1c3t3a** [comment]
Did you experience with an earlier version as well?

**Comment by editso** [comment]
> Did you experience with an earlier version as well?

Yes, I used 0.2.4 earlier but this version has the same error

**Comment by 1c3t3a** [comment]
Oke, first of all are you sure the server is configured correctly? The url mentions a `/ws/`, does it help to connect via `ws://` instead of `http://`, are you sure the `node` namespace exists? Could you also explain more about your environment, I am not really familiar with it. I expect that in your environment there are no formatting outputs, are there? This would help to further narrow down the problem (e.g. something like special unwrap errors on a result).

**Comment by editso** [comment]
As long as I don't use musl for packing I don't have any problems

**Comment by editso** [comment]
> Oke, first of all are you sure the server is configured correctly? The url mentions a `/ws/`, does it help to connect via `ws://` instead of `http://`, are you sure the `node` namespace exists? Could you also explain more about your environment, I am not really familiar with it. I expect that in your environment there are no formatting outputs, are there? This would help to further narrow down the problem (e.g. something like special unwrap errors on a result). 

As long as I don't use musl for packing I don't have any problems

**Comment by editso** [comment]
> > Oke, first of all are you sure the server is configured correctly? The url mentions a `/ws/`, does it help to connect via `ws://` instead of `http://`, are you sure the `node` namespace exists? Could you also explain more about your environment, I am not really familiar with it. I expect that in your environment there are no formatting outputs, are there? This would help to further narrow down the problem (e.g. something like special unwrap errors on a result). 
> 
> As long as I don't use musl for packing I don't have any problems

I don't think it should have a segment error even if it is caused by these problems

**Comment by editso** [comment]
> Oke, first of all are you sure the server is configured correctly? The url mentions a `/ws/`, does it help to connect via `ws://` instead of `http://`, are you sure the `node` namespace exists? Could you also explain more about your environment, I am not really familiar with it. I expect that in your environment there are no formatting outputs, are there? This would help to further narrow down the problem (e.g. something like special unwrap errors on a result). 

The problem occurred when using musl packaging and I thought it was worth trying musl packaging to verify the problem

**Comment by editso** [comment]
> > Oke, first of all are you sure the server is configured correctly? The url mentions a `/ws/`, does it help to connect via `ws://` instead of `http://`, are you sure the `node` namespace exists? Could you also explain more about your environment, I am not really familiar with it. I expect that in your environment there are no formatting outputs, are there? This would help to further narrow down the problem (e.g. something like special unwrap errors on a result). 
> 
> The problem occurred when using musl packaging and I thought it was worth trying musl packaging to verify the problem

If necessary I will download your source code and try to debug it and find out what the problem is

**Comment by 1c3t3a** [comment]
Do you have any updates on this? I don't really know the process of "packaging with musl", if you could further explain this I might be able to help
