### ISSUE TITLE
Project Examples?

### ISSUE THREAD

**Issue by conner-replogle** [1c3t3a/rust-socketio#156]
Has anyone used this for a project and would like to share an example for me that is a little more complex than the provided one? I need it for a project I'm working on but I can't figure out how to use the .on() functions to modify data that is scoped outside of it. I may be dumb, as my experience with rust is only novel but I've looked all over and don't see a way around this. For example, if I were to create a snake game and wanted to use this library for multiplayer how could I modify the snake struct inside of a socket .on method. I really just need one example of modifying data that isn't scoped to the .on function and ill be able to make my project work.
```
  let mut snake = Snake{
        x: 1,
        y: 1,
    };
    ClientBuilder::new("http:://localhost:3001")
        .namespace("/")
        .on("update", |p,c|{
            //get the position from the payload: Payload,
            let new_pos_x = 4;
            let new_pos_y = 4;
            //this causes a error since the closure could outlive snake
            snake.x = new_pos_x;
            snake.y = new_pos_y;
        })
        .on("error", |err, _| eprintln!("Error: {:#?}", err))
        .connect();
```
ps. This is just very very simple code I wrote to show what I'm talking about this is not how I would be actually structuring it.

**Comment by 1c3t3a** [comment]
Hi @conner-replogle ;) What you're looking for is interior mutability in a multithreaded context.
To make your specific piece of code work you would look for something similar to the following:
```rust
let snake = Arc::new(Mutex::new(Snake { x: 1, y: 1 }));

// Clone the Arc (increasing the ref count by one)
let snake_clone = snake.clone();
let client = ClientBuilder::new("http:://localhost:3001")
    .namespace("/")
    .on("update", move |p, c| {         
        // get the position from the payload: Payload,
        let new_pos_x = 4;
        let new_pos_y = 4;
        // lock the mutex and mutually access the underlying snake
        let mut lock_snake = snake_clone.lock().expect("Error with poisoned lock");
        lock_snake.x = new_pos_x;
        lock_snake.y = new_pos_y;
    })
    .on("error", |err, _| eprintln!("Error: {:#?}", err))
    .connect();

// You're still able to mutate the value afterwards
let mut lock = snake.lock().unwrap();
lock.x = 43;
```
The callback provided inside `on` is executed inside another thread, which gets created as soon as a new message is received. As you might know, mutually accessing a value from multiple threads requires locking (through the `Mutex` type in this example). 

For some good sources on the topic and the reason why you need `Arc` you might want to read further explanations:
- https://www.ralfj.de/projects/rust-101/part15.html
- https://doc.rust-lang.org/book/ch16-03-shared-state.html

**Comment by 1c3t3a** [comment]
Does this answer your question?

**Comment by conner-replogle** [comment]
> Does this answer your question?

yes thank you!
