### ISSUE TITLE
Add a test suite that tests against the official engine/socketio api

### ISSUE THREAD

**Issue by 1c3t3a** [1c3t3a/rust-socketio#2]
There is already the file example/engine.io.js file that could be run via node in order to start up a server. I currently use it to test the client, but not in an automated way.

**Comment by kw-fn** [comment]
the current outline is to start a docker-compose instance with the node
socket.io server in one container and the socket.io test code in another one
which will then be executed within GitHub Actions

**Comment by kw-fn** [comment]
this is still a work in progress with errors in the build process I'm looking
into the syntax of existing docker and yml files for obvious mistakes

**Comment by 1c3t3a** [comment]
The current suite just runs the socket.io server, it would be nice to add another container to the docker-compose file running the engine.io server.
