### ISSUE TITLE
String payload doesn't have proper decoded utf-8

### ISSUE THREAD

**Issue by milandekruijf** [1c3t3a/rust-socketio#215]
My string payload contains weird characters for returned unicode symbols.

For example I should receive '™', I am getting 'â¢', and for '★' I am getting 'â'.

I've tried everything but with no success so I am now manually replacing them. I am pretty new to rust and to low level programming, so I might be doing something wrong.

**Comment by SSebo** [comment]
A demo to reproduce the bug will be easy to fix.

**Comment by milandekruijf** [comment]
I don't have a demo for you. I am connected to an api. I do know the api returns everything correctly because it does work with nodejs's socketio client.

**Comment by SSebo** [comment]
@1c3t3a I make a PR

**Comment by 1c3t3a** [comment]
Thank you @SSebo, I would recommend trying out the patch by importing the dependency as follows: `rust_socketio = { git = "https://github.com/SSebo/rust-socketio", branch = "utf8"}`.

**Comment by milandekruijf** [comment]
I have, and it worked. Thank you so much!
