### ISSUE TITLE
thread '<unnamed>' panicked at 'EngineIO Error'

### ISSUE THREAD

**Issue by milandekruijf** [1c3t3a/rust-socketio#216]
I have the exact same issue as closed issue #166. Are there any updates? I am not sure why it was closed.

EDIT: Something else I noticed it that I don't receive events from the server anymore after some time.

**Comment by SSebo** [comment]
> EDIT: Something else I noticed it that I don't receive events from the server anymore after some time.

the thread which is respond to handle packet to callback is panic https://github.com/1c3t3a/rust-socketio/blob/main/socketio/src/client/builder.rs#L271

anything error about the underlying websocket connection will cause this thread panic

**Comment by milandekruijf** [comment]
I wouldn't know what to do then. It works perfectly on the nodejs implementation of socketio. It happens so sudden, without any reason.

**Comment by 1c3t3a** [comment]
In software, nothing happens without any reason. The nodejs implementation contains logic for reconnecting when the underlying websocket connection is closed for some reason (laggy network or whatever). This implementation doesn't have such a logic, but @SSebo is currently working on it.

**Comment by milandekruijf** [comment]
Oh, I didn't know that. I look forward to having that feature.

**Comment by milandekruijf** [comment]
The error indicates that the WebSocket control frame was fragmented btw. Just thought it would maybe be helpful to know.

**Comment by milandekruijf** [comment]
I even got 'thread '<unnamed>' panicked at 'internal error: entered unreachable code: Won't happen as we open the connection beforehand',' after a little while. How is that even possible.

**Comment by milandekruijf** [comment]
All my issues seem to be entirely fixed after running the socket in a blocking allowed thread using `tokio::task::spawn_blocking` method. I didn't really get an error message before to let me know that I had to do that, but now I did, so it might've been a recent push. (https://github.com/1c3t3a/rust-socketio/blob/4eea9b741caae207cf1f8c5df97022eb2b59d482/engineio/src/transports/websocket_secure.rs#L34)

**Comment by milandekruijf** [comment]
Nevermind. I actually got the error again after it running for like 7 hours.

**Comment by SSebo** [comment]
@1c3t3a @milandekruijf maybe we should add some tracing log.

**Comment by milandekruijf** [comment]
I still have this issue now. Nothing works. It's as if even having a single other thread running, the entire thing breaks. That's what it feels like. I even tried @SSebo's reconnect fork but that doesn't work either. Any help?

**Comment by milandekruijf** [comment]
I might've managed to get it to work like this

```rust
tokio::task::spawn_blocking::<_, Result<socketio::Client>>(|| {
    let client = socketio::ClientBuilder::new(URL)
        .transport_type(TransportType::Websocket)
        .on("open", |_, _| {
            info!("Connected");
        })
        .on("error", |err, _| eprintln!("Error: {:#?}", err))
        .connect()?;

    loop
    {}

    Ok(client)
})
.await??;
```

Why not just block when listening for messages. I think you should allow the user to choose whether or not to put it in a different thread or not.

**Comment by milandekruijf** [comment]
So yeah, the problem is that it goes out of scope. So all I can do is block the thread forever. (I think). If there's something better to do lmk.

**Comment by 1c3t3a** [comment]
This behaviour is now different with #229, this won't panic but rather try to reconnect on a transport error. I am closing this bug as it is outdated.
