### ISSUE TITLE
Set url parameters for reconnecting

### ISSUE THREAD

**Issue by tyilo** [1c3t3a/rust-socketio#251]
I need to connect a socket.io that on connection will check if a specific query parameter contains a valid JWT token (which is not expired).

During the lifetime of the client using this library, the JWT token will expire. I can retrieve a fresh token which is not expired, but I need to update the url that rust-socketio uses for reconnection, otherwise reconnection will fail.

I see two different approaches for implementing this:
1. Add a public `set_reconnect_url` function to `Client`.
2. Add a `on_reconnect` function to `ClientBuilder` with the signature `fn(ClientBuilder) -> ClientBuilder`. Before the client tries to reconnect it will use the reconnect handler (if specified) to get a modified `ClientBuilder`. This handler can then change the url, opening headers, auth, etc...

I have implemented option 1 in https://github.com/1c3t3a/rust-socketio/pull/252

**Comment by 1c3t3a** [comment]
Ough.. I think this is really odd behavior that doesn't really sound like proper API design. Have you tried using something like HTTP 301 status codes to do redirection to different endpoint? I am not sure if I like the idea of redesigning the public interface for this "edge-casey" use case.

**Comment by tyilo** [comment]
> Ough.. I think this is really odd behavior that doesn't really sound like proper API design. Have you tried using something like HTTP 301 status codes to do redirection to different endpoint? I am not sure if I like the idea of redesigning the public interface for this "edge-casey" use case.

That doesn't seem to work with authentication.

Also the javascript socket.io library supports this.

**Comment by 1c3t3a** [comment]
Can you point me to the JS implementation of this?

**Comment by tyilo** [comment]
The official socket.io documentation has an example of updating the query parameters on reconnect[^1]:
```js
socket.io.on("reconnect_attempt", () => {
  socket.io.opts.query.x++;
});
```

I actually also only need the ability to change the query parameters, not the full url.

[^1]: https://socket.io/docs/v4/client-options/#query

**Comment by rageshkrishna** [comment]
This seems to be a valid use case. I'm running into the same auth problem myself now. When a reconnect is required, I should be able to pass a new auth value. It seems like a callback for reconnect would solve this and a few other problems, like the app needing to know when a reconnect is about to happen.

**Comment by tyilo** [comment]
@rageshkrishna I think you should open a new issue, as this issue has been fixed.
