### ISSUE TITLE
`ClientBuilder::on(_any)` should be able to take `!Sync` functions too

### ISSUE THREAD

**Issue by ZetaNumbers** [1c3t3a/rust-socketio#263]
There's no reason to keep callbacks under `std::sync::RwLock` if it's `FnMut`, so exclusive access is needed anyways. `std::sync::Mutex` should be used instead as it implements `Sync` regardles if the wrapped value implements `Sync` or not.

**Comment by 1c3t3a** [comment]
Sounds like a fair assessment, thanks for the issue. Do you mind submit a PR for that?
