### ISSUE TITLE
Async ClientBuilder dose not impl reconnect

### ISSUE THREAD

**Issue by veerapatyok** [1c3t3a/rust-socketio#291]
I use `tokio` and need `reconnect` option for `async` ClientBuilder but blocking ClientBuilder have one.

Can implement reconnect for `async` version?

**Comment by ehuff700** [comment]
Please give me feedback in [this PR for this issue](https://github.com/1c3t3a/rust-socketio/pull/357)

**Comment by kitgxrl** [comment]
Would love to see some progress on this! Async reconnection is pretty important, I would attempt to implement it myself but the async Client(Builder) and non-async Client(Builder) are structured very differently...

**Comment by rageshkrishna** [comment]
@1c3t3a I'm willing to take a stab at this. Please let me know if you have some thoughts on how this should be implemented. That would be useful as a starting point, just to be sure that I don't go off the deep end trying to make this work. Thanks!

**Comment by rageshkrishna** [comment]
Thanks for the tips @1c3t3a!

I started digging into this today and have run into some problems that I need to figure out how to solve. The big difference is that the sync and async clients work very differently with regards to the callbacks. For example, the async client sends clones of `self` to the callbacks, whereas the sync client has a `RawClient` and this is what it replaces internally when a reconnection happens. It looks like I'll have to consider a similar approach or somehow replace just its `InnerSocket` when reconnecting. I'm also running into some difficulties with ownership when trying to make Client own a ClientBuilder that I need to resolve.

Not to say that any of what I've seen so far is impossible to get around; just that it appears to be much more involved than I had hoped 😄. I'll keep hacking away at it until I have something that (hopefully) doesn't involve any breaking changes. I'll keep you posted.

**Comment by rageshkrishna** [comment]
@1c3t3a I've got a [draft PR](https://github.com/rageshkrishna/rust-socketio/pull/1). It's still work-in-progress and is missing tests, but I wanted to get some feedback on the approach before going further. Let me know what you think. Thanks!

**Comment by kitgxrl** [comment]
I had managed to get async reconnection working for my use case by wrapping the `InnerSocket` in `RwLock` and adding the `poll_callback` logic to the thread spawned in `ClientBuilder::connect`. The reconnection logic was more or less the same. However my implementation is probably messy at best... it heavily relies on storing the reconnection related fields to the async `Client` and passing all of them when it's created which likely isn't ideal.

Also had some weird quirks where the async client's reconnection just didn't behave like the sync client in some cases...

**Comment by rageshkrishna** [comment]
Thanks @kitgxrl. My approach is somewhat the same. So far I've managed to keep most of it inside `ClientBuilder`'s thread. My client has access to the builder so it can request a new `InnerSocket` when it needs one without knowing the internals of how that gets constructed. Do let me know if you have some feedback on my PR. This is my first stab at it, so it's quite possible that I've missed something.

**Comment by kitgxrl** [comment]
@rageshkrishna Absolutely! I'll give it a shot when I get home later. Your implementation is likely already better considering I underestimated how much the structure of the async client really affected the reconnection logic and I just kept adding onto the mess instead of just starting over lol
