### ISSUE TITLE
error add overflow when reconnect

### ISSUE THREAD

**Issue by veerapatyok** [1c3t3a/rust-socketio#338]
I set `max_reconnect_attempts` is None(default) to `infinity`, delay is default and I got error `add overflow` in file `client.rs` line 164 (sorry an error are gone).

I see variable `reconnect_attempts` has type `u8` (max is 255) and I think when reconnect is infinity it may get error `add to overflow`

Is it possible change `reconnect_attempts += 1` to `reconnect_attempts.wrapping_add(1)` or ignore `add` when set `max_reconnect_attempts` is None ?

Thank you

**Comment by 1c3t3a** [comment]
Fair assessment! Sounds like a reasonable fix, would you be interested in a PR? Otherwise I could open one. Although I would say your client is in a weird state if it reaches 255 reconnects, taking into account the exponential backoff.

**Comment by veerapatyok** [comment]
> Fair assessment! Sounds like a reasonable fix, would you be interested in a PR? Otherwise I could open one. Although I would say your client is in a weird state if it reaches 255 reconnects, taking into account the exponential backoff.

ok and please grant me

**Comment by 1c3t3a** [comment]
You need to fork the repository and then create a PR :) The process is explained here: https://docs.github.com/de/get-started/quickstart/fork-a-repo

**Comment by veerapatyok** [comment]
@1c3t3a I created PR https://github.com/1c3t3a/rust-socketio/pull/341 and please review

**Comment by 1c3t3a** [comment]
Closed in #341
