### ISSUE TITLE
add macro to simplyfy async callback define

### ISSUE THREAD

**Issue by shenjackyuanjie** [1c3t3a/rust-socketio#395]
now, defining a async callback require a big bunch a code like this

https://github.com/1c3t3a/rust-socketio/blob/main/socketio/src/asynchronous/client/builder.rs#L144-L168

```rust
use rust_socketio::{asynchronous::ClientBuilder, Payload};
use futures_util::FutureExt;

#[tokio::main]
async fn main() {
    let callback = |payload: Payload, _| {
            async move {
                match payload {
                    Payload::Text(values) => println!("Received: {:#?}", values),
                    Payload::Binary(bin_data) => println!("Received bytes: {:#?}", bin_data),
                    // This is deprecated use Payload::Text instead
                    Payload::String(str) => println!("Received: {}", str),
                }
            }
            .boxed() // <-- this makes sure we end up with a `BoxFuture<_>`
        };

    let socket = ClientBuilder::new("http://localhost:4200/")
        .namespace("/admin")
        .on("test", callback)
        .connect()
        .await;
}
```

so that it can handled by inside

but, with the help of a little macro like this

```rust
macro_rules! wrap_callback {
    ($f:expr) => {
        |payload: Payload, client: Client| $f(payload, client).boxed()
    };
}

macro_rules! wrap_any_callback {
    ($f:expr) => {
        |event: Event, payload: Payload, client: Client| $f(event, payload, client).boxed()
    };
}
```
we can then just define the callback like this

```rust
pub async fn callback_any(event: Event, payload: Payload, client: Client) {}
pub async fn callback(payload: Payload, client: Client) {}

let socket = ClientBuilder::new(host)
        .on_any(wrap_any_callback!(callback_any))
        .on("message", wrap_callback!(callback))
        .connect()
        .await
        .expect("Connection failed");
```
which is verry simple

also, the `AsyncFnMut` trait is in nighly, so we can wait for it to stable

I have tested the macro in a real project( where I also tested the muly_palyload PR #392 )

https://github.com/shenjackyuanjie/icalingua-python-bot/blob/main/ica-rs/src/main.rs#L24-L34

so where wound the macro go? and should I rename it?
like `wrap_async_callback` ?

**Comment by rageshkrishna** [comment]
I like this idea. It would be a nice stop-gap until `AsyncFnMut` is available. May I suggest calling them `callback!` and `callback_any!`? The `wrap_` seems superfluous.

**Comment by 1c3t3a** [comment]
Sounds fair! I am open for PRs regarding this :)

**Comment by shenjackyuanjie** [comment]
> Sounds fair! I am open for PRs regarding this :)

here comes the PR! #399

**Comment by shenjackyuanjie** [comment]
done with 0.5.0 release
