### ISSUE TITLE
Allow async connections to update auth when reconnecting

### ISSUE THREAD

**Issue by rageshkrishna** [1c3t3a/rust-socketio#401]
#291 will add support for reconnections to the async client. Once that lands, we should give the app an opportunity to update its connection settings (address, auth, etc.), because the original settings may not be valid by the time a reconnection is required.

Adding something like an `on_reconnect` callback on the builder would allow us to do this without any breaking changes, like so:

```rust
let client = rust_socketio::asynchronous::ClientBuilder::new(server)
    .on_reconnect(|| {
        async move {
            // Do something async...
            sleep(Duration::from_secs(5)).await;

            // Generate and return new config
            let mut settings = ReconnectSettings::new();
            settings.auth(json!({"token": "foo"}));
            settings
        }
        .boxed()
    })
```

**Comment by 1c3t3a** [comment]
Hey @rageshkrishna, just checking in with you: Do you plan to implement this as well? Just want to know if I should release a new version of the crate already or wait till this is in? Anyways it's also oke if you're not the one implementing this.

**Comment by rageshkrishna** [comment]
Yes, I'll have a PR for this right after the weekend. It would be nice if the release could wait for this because the reconnect feature feels like it's only half done without the ability to authenticate successfully.

Let me know if you have any thoughts on the proposed API for this.

**Comment by 1c3t3a** [comment]
Alright, perfect! The API looks good to me, it is nice and extensible. We could potentially also add it to the sync version later as well :)

**Comment by rageshkrishna** [comment]
@1c3t3a I've opened a PR for this one. Please take a look when you can. Thanks!
