### ISSUE TITLE
How to close or disconnect a socket?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [1c3t3a/rust-socketio#43]
Hi!

Is there any way to close or disconnect an existing socket?

Thanks in advance!

**Comment by 1c3t3a** [comment]
Hei there! I don't really know how this happens, but I actually missed a disconnect method on the `Socket` struct. For now, an ugly `drop(socket);` will do the disconnect. I will add the method and come up with a new version tomorrow!

**Comment by ZaMaZaN4iK** [comment]
Yeah, I've already ended up with `drop(socket)` hack. Will be great to see a new version - thanks in advance for the fix!

**Comment by 1c3t3a** [comment]
Hei, I've just released a new version (v0.2.3) that fixes this issue!
