### ISSUE TITLE
[bug] unable to connect to an http based socketio server

### ISSUE THREAD

**Issue by shenjackyuanjie** [1c3t3a/rust-socketio#442]
it can't connect to this socketio server

https://github.com/msgbyte/tailchat/blob/master/server/mixins/socketio.mixin.ts#L542-L550

even with disable msgpack parser

**Comment by 1c3t3a** [comment]
Can you please give more context? E.g. what error are you observing.

**Comment by shenjackyuanjie** [comment]
It's file, it's mine problem
whish you have a happy day(
