### ISSUE TITLE
Allow headers in ReconnectSettings

### ISSUE THREAD

**Issue by DanielChabrowski** [1c3t3a/rust-socketio#462]
Hi!

`ReconnectSettings` currently allows modification of an address and authentication data however servers might also require different or refreshed headers like e.g if server requires bearer token as a header for authentication instead.

Would this project consider adding `opening_headers` it to the ReconnectSettings struct?

**Comment by ctrlaltf24** [comment]
Seems reasonable, PRs are welcome!
