### ISSUE TITLE
Deserialization of Handshake is failing

### ISSUE THREAD

**Issue by Halkcyon** [1c3t3a/rust-socketio#49]
👋🏼 hello!

I've started experimenting with the crate this weekend and I'm having trouble integrating with a socketio server written in php.  The `Error` event is being triggered on every connection.  I believe I've narrowed the error down to this section:

https://github.com/1c3t3a/rust-socketio/blob/d2bdd324d05f785462d97e6c73170767621144e4/src/engineio/transport.rs#L191-L230

What I'm seeing locally is this:

```rs
HandshakeError("\u{0}\u{1}\u{0}\u{1}�0{\"sid\":\"c7f0f5c5b72fd8410429e568\",\"upgrades\":[\"websocket\"],\"pingInterval\":25000,\"pingTimeout\":60000}")
```

I can't tell why there's garbage in front of the JSON payload, but I'm able to connect to this same socketio server with a .NET implementation.

**Comment by 1c3t3a** [comment]
Mhh.. that looks weird, what socket.io version is the server running on? The 'garbage' in front of the json payload might come from an older socket.io version where different separators were used. Usually the client tells which protocol version it's using upon connection, but maybe the server ignores this and just starts to send his opening packet.

**Comment by 1c3t3a** [comment]
Is the php server open source? We could take a look at the implementation then, this might narrow down the error.

**Comment by Halkcyon** [comment]
```php
use PHPSocketIO\SocketIO;
use Workerman\Timer;
use Workerman\Worker;
```

I believe these are the relevant imports.  The server is started using the `SocketIO` class without any configuration.

Dependency version appears to be `"workerman/phpsocket.io": "^1.1"`

**Comment by 1c3t3a** [comment]
Alright, I looked at their packet serialization and it's actually done the socketio 2.x way (note the ":" as packet separator): 
https://github.com/walkor/phpsocket.io/blob/bc94451683b3467b28d7441fbc0fc1b7461f5db4/src/Engine/Parser.php#L102-L136

There is also an open issue [#262](https://github.com/walkor/phpsocket.io/issues/262) which mentions that this is in fact an old version of the protocol and that they don't plan to update within the next time. I'm sorry, but I don't have plans to support older versions either, but if someone is willing to implement it, I am happy for contributions. You're .NET dependency probably supports the 2.x version as well.

**Comment by Halkcyon** [comment]
@1c3t3a bummer!  I really appreciate your investigation into the matter.  I shall go advocate on that issue then (and maybe get a php friend to submit a patch 😉)
