### ISSUE TITLE
Requests only going through sometimes?

### ISSUE THREAD

**Issue by Jefff000** [1c3t3a/rust-socketio#67]
**For some reason, requests only go through sometimes and with little consistency. Im not too sure why? Maybe because its upgrading but Im a bit stuck...**

**Client-side Code**
```
use rust_socketio::{Payload, Socket, SocketBuilder};
use serde_json::json;

fn main() {
    let callback = |payload: Payload, mut socket: Socket| {
        match payload {
            Payload::String(str) => println!("Received: {}", str),
            Payload::Binary(bin_data) => println!("Received bytes: {:#?}", bin_data),
        }
        socket
            .emit("message", json!("aquired"))
            .expect("Server unreachable")
    };

    let mut socket = SocketBuilder::new("https://censored.herokuapp.com")
        .on("message", callback)
        .on("error", |err, _| eprintln!("Error: {:#?}", err))
        .connect()
        .expect("Connection failed");

    socket.emit("message", json!("cool message one")).expect("Server unreachable");
    socket.emit("message", json!("cool message two")).expect("Server unreachable");
    
    socket.emit("message", json!("cool message three")).expect("Server unreachable");
    socket.emit("message", json!("cool message four")).expect("Server unreachable");
}

```
**Serverside Code**
```
const cors = require('cors');
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http, {
	allowEIO3: true,
	cors: {
		origin: "*"
	}
});

const port = process.env.PORT || 3000;

io.on('connection', (socket) => {
	console.log("user connect");
	
	socket.on('message', function(data) {
		io.emit('message', data);
		console.log(data);
	});

	socket.on('clear', function clear() {
		io.emit('clear');
	});
});

http.listen(port, () => {
	console.log(`Socket.IO server running at http://localhost:${port}/`);
});

```

https://user-images.githubusercontent.com/83432863/128225249-f433997c-d36f-4ac3-aabb-8c5c721b09f9.mp4

**Comment by nshaaban-cPacket** [comment]
Is this reproducible using http (rather than https)? @Jefff000

**Comment by 1c3t3a** [comment]
Could you run the server with DEBUG=1? Then we see which Transport Layer is used!

**Comment by Jefff000** [comment]
[shoutbox-nullus-logs-1628112538106.txt](https://github.com/1c3t3a/rust-socketio/files/6934495/shoutbox-nullus-logs-1628112538106.txt)

Here is a log

**Comment by Jefff000** [comment]
Here is a log
[log.txt](https://github.com/1c3t3a/rust-socketio/files/6934500/log.txt)

**Comment by nshaaban-cPacket** [comment]
Looks like the underlying websocket is getting closed before the fourth message can be sent. Your example works fine on my machine. @1c3t3a any ideas?

**Comment by 1c3t3a** [comment]
Mhh... this looks weird. What I find especially odd is that the server registers the client to a namespace, but then acts like no one joined the namespace on message one:
```
2021-08-04T21:27:05.376017+00:00 app[web.1]: 2021-08-04T21:27:05.375Z socket.io-parser decoded 0 as {"type":0,"nsp":"/"}
2021-08-04T21:27:05.376567+00:00 app[web.1]: 2021-08-04T21:27:05.376Z socket.io:client connecting to namespace /
2021-08-04T21:27:05.376911+00:00 app[web.1]: 2021-08-04T21:27:05.376Z socket.io:namespace adding socket to nsp /
2021-08-04T21:27:05.378390+00:00 app[web.1]: 2021-08-04T21:27:05.378Z engine:ws received "42["message","cool message one"]"
2021-08-04T21:27:05.378977+00:00 app[web.1]: 2021-08-04T21:27:05.378Z engine:socket received packet message
2021-08-04T21:27:05.379371+00:00 app[web.1]: 2021-08-04T21:27:05.379Z socket.io-parser decoded 2["message","cool message one"] as {"type":2,"nsp":"/","data":["message","cool message one"]}
2021-08-04T21:27:05.379619+00:00 app[web.1]: 2021-08-04T21:27:05.379Z socket.io:client no socket for namespace /
```

Message two and three work properly but message four fails to get through, which should error on the client side if there's a problem with the transportation as we're doing this in a blocking operation.
The fact that the server closes with the reason `transport closed` is normal, as the connection just gets cut off when the client is dropped.

In which environment is the server running? Is there maybe some sort of proxy in between? 

On my machine this is running through as well, with all packets being received in the end.

**Comment by Jefff000** [comment]
Just a standard Heroku NodeJS Server~ could there be some sort of delay added?

**Comment by 1c3t3a** [comment]
Mhh... Which version of the server and the client are used? You could try to add a delay by sleeping between opening the connection and the first message. But I think this shouldn't be a problem as the `connect` method only returns after everything went through and the connection got upgraded.

**Comment by Jefff000** [comment]
Can you elaborate on what you mean by the version of the server & client.

Adding a delay in fact does not help.

**Comment by 1c3t3a** [comment]
Ah strange.... By version I mean which version on crates.io of the rust client (newest is 0.2.4) you use. On the serverside it's the same thing, just which version from npm you use (the newest:  4.0.0).

**Comment by Jefff000** [comment]
Both are running the latest versions of crates.io & npm

**Comment by Jefff000** [comment]
~~ Any news on this?

**Comment by 1c3t3a** [comment]
Mhh I'm sorry but not really. Mostly as I don't really have an environment to test this issue. As I said, the exact same code runs through on my machine. It could be that something odd is happening with the connection to the server when running on heroku, but I can't test that. 

Currently there is a lot of refactoring going on by @nshaaban-cPacket. He doesn't really change the logic of connections, but I think it might be a good idea to try it out as soon as the new version is released (take a look at #85).

**Comment by Jefff000** [comment]
@nshaaban-cPacket 

Wow! This fixed it. 

Thanks for the explanation.

**Comment by 1c3t3a** [comment]
Nice! But this means that there is a bug in the websocket connection you have with the server. Just to keep that in mind ;) I will also remember this and maybe reopen the issue if there is a bug on the client side.

**Comment by nshaaban-cPacket** [comment]
> @nshaaban-cPacket
> 
> Wow! This fixed it.
> 
> Thanks for the explanation.

To clarify did removing allowEIO3 fix it, or did restricting the transport to just polling fix it?
