### ISSUE TITLE
Multiple Attachment Support

### ISSUE THREAD

**Issue by nshaaban-cPacket** [1c3t3a/rust-socketio#90]
Seems like there is only a field for [one attachment](https://github.com/1c3t3a/rust-socketio/blob/d421946915b1aa6cf95b65624853ffd0717747b6/src/socketio/packet.rs#L24) (and [only one stored](https://github.com/1c3t3a/rust-socketio/blob/d421946915b1aa6cf95b65624853ffd0717747b6/src/socketio/transport.rs#L276)), despite [storing how many attachments](https://github.com/1c3t3a/rust-socketio/blob/d421946915b1aa6cf95b65624853ffd0717747b6/src/socketio/packet.rs#L26) a packet has. Was there a reason for this @1c3t3a or is it just not implemented yet?

TODO:
- [ ] Change binary data structure to a list
- [ ] Consume as many packets as required

**Comment by 1c3t3a** [comment]
It's actually not yet implemented. That's defenetly something that should be added. In the current setup this would lead to just having the last binary payload as binary_payload of a packet.
