### ISSUE TITLE
Limit transport to websockets

### ISSUE THREAD

**Issue by namxam** [1c3t3a/rust-socketio#94]
Is it possible to specify the transport before initializing a connection? We have a service which only supports websocket connections and no long polling.

**Comment by 1c3t3a** [comment]
That's currently not supported, but a feature that's rather easy to add. There is currently a lot of refactoring going on by @nshaaban-cPacket, but I'm sure we could add this to the list of features. Currently the first request is a http request to the server, receiving a handshaking packet in response. If this packet mentions an upgrade possibility, the client upgrades immediately.

**Comment by 1c3t3a** [comment]
How urgent is your need for this? We could maybe add this before working on a server implementation after the first refactoring PRs hit main.

**Comment by nshaaban-cPacket** [comment]
@namxam released in 0.3.0-alpha-1 https://docs.rs/rust_socketio/0.3.0-alpha.1/rust_socketio/struct.SocketBuilder.html#method.transport_type

**Comment by 1c3t3a** [comment]
Closing this as it is now resolved.
