### ISSUE TITLE
[Help] Respond to incoming event with a result payload?

### ISSUE THREAD

**Issue by namxam** [1c3t3a/rust-socketio#95]
My server emits an event and is expecting a return value from the receiving client. I see there is `emit_with_ack()`, but can I somehow send a payload when processing an incoming event?

**Comment by 1c3t3a** [comment]
Yes, looking at the [function signature](https://docs.rs/rust_socketio/0.2.4/rust_socketio/struct.Socket.html#method.emit_with_ack), the parameter `event` takes an `FnMut(Payload, Socket)`. The `Payload` is the payload send by the server and the `Socket` is an instance of the socket. That way you could use the socket inside the Callback, e.g. like that:

```rust
let mut socket = SocketBuilder::new("http://localhost:4200")
    .on("foo", |payload: Payload, _| println!("Received: {:#?}", payload))
    .connect()
    .expect("connection failed");



let ack_callback = |message: Payload, my_socket: Socket| {
    match message {
        Payload::String("send me a message!!!") => my_socket.emit("foo", "answer is 42".into()),
        Payload::String(s) => println!("{}", s),
        _ => (),
   }    
};

let payload = json!({"token": 123});
socket.emit_with_ack("foo", payload, Duration::from_secs(2), ack_callback).unwrap();
```

**Comment by 1c3t3a** [comment]
Does this solve your issue? Or did you mean something else?
