### ISSUE TITLE
Auto-reconnect on disconnects

### ISSUE THREAD

**Issue by namxam** [1c3t3a/rust-socketio#96]
From what I have seen, most client libraries support auto-reconnects. It would be really nice to have this 🙈

**Comment by SSebo** [comment]
@1c3t3a   I would like to help, here is my branch https://github.com/SSebo/rust-socketio/tree/reconnect, still need `backoff` and `retry` functionality.

**Comment by 1c3t3a** [comment]
Great! I appreciate the help!

**Comment by 1c3t3a** [comment]
Implemented in #229.
